/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.*;
import org.xml.sax.SAXException;

/**
 *
 * @author francis
 */
public class principal extends javax.swing.JFrame 
{
    private String rutafichero = "src/XML/discos.xml";

    /**
     * Creates new form principal
     */
    public principal() 
    {
        initComponents();
        
        lNombreFicheroXML.setText("Fichero: " + rutafichero);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bElegirFicheroXML = new javax.swing.JButton();
        bMostrarNodos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lNombreFicheroXML = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEtiquetas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mostrar nodos de un fichero XML");
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));

        jPanel1.setLayout(new java.awt.BorderLayout());

        bElegirFicheroXML.setText("Elegir fichero");
        bElegirFicheroXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bElegirFicheroXMLActionPerformed(evt);
            }
        });
        jPanel3.add(bElegirFicheroXML);

        bMostrarNodos.setText("Mostrar nodos");
        bMostrarNodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMostrarNodosActionPerformed(evt);
            }
        });
        jPanel3.add(bMostrarNodos);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        lNombreFicheroXML.setText("Fichero: ");
        jPanel2.add(lNombreFicheroXML, java.awt.BorderLayout.PAGE_START);

        taEtiquetas.setEditable(false);
        taEtiquetas.setColumns(20);
        taEtiquetas.setRows(5);
        jScrollPane1.setViewportView(taEtiquetas);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bMostrarNodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMostrarNodosActionPerformed
        
        taEtiquetas.setText("");
        
        try 
        {
            FicheroXML fichero = new FicheroXML(rutafichero);
            fichero.cargarFicheroXML();
                    
            fichero.mostrarNodosFichero(taEtiquetas);
            
            taEtiquetas.append("\nCantidad total de nodos: " + fichero.contarNodosFichero());
        } 
        catch (ParserConfigurationException error01) 
        {
            System.out.println("Error 01: " + error01.toString());
        }
        catch (SAXException error02) 
        {
            System.out.println("Error 02: " + error02.toString());
        } 
        catch (IOException error03)
        {
            System.out.println("Error 03: " + error03.toString());
        }
    }//GEN-LAST:event_bMostrarNodosActionPerformed

    private void bElegirFicheroXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bElegirFicheroXMLActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Ficheros XML", "xml");
        chooser.setFileFilter(filter);
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) 
        {
            rutafichero = chooser.getSelectedFile().getAbsolutePath();
            lNombreFicheroXML.setText("Fichero: " + rutafichero);
        }
    }//GEN-LAST:event_bElegirFicheroXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bElegirFicheroXML;
    private javax.swing.JButton bMostrarNodos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNombreFicheroXML;
    private javax.swing.JTextArea taEtiquetas;
    // End of variables declaration//GEN-END:variables
}
